[package]
name = "allay-plugin-host"
version = "0.1.0"
edition = "2024"

[dependencies]
wasmtime.workspace = true
wasmtime-wasi.workspace = true
allay-base = { path = "../allay-base" }
axum.workspace = true
tokio.workspace = true
async-trait.workspace = true