[package]
name = "allay-plugin-api"
version = "0.1.0"
edition = "2024"

[dependencies]
plugin-macro = { path = "crates/plugin-macro" }
wit-bindgen.workspace = true
urlencoding.workspace = true
axum.workspace = true
async-trait.workspace = true
