[package]
name = "allay-plugin-api"
version = "0.1.0"
edition = "2024"

[dependencies]
plugin-macro = { path = "crates/plugin-macro" }
allay-base = { path = "../allay-base" }
wit-bindgen.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
